apiVersion: v1
kind: Service
metadata:
  name: {{ include "coordworks.fullname" . }}
  labels:
    {{- include "coordworks.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "coordworks.selectorLabels" . | nindent 4 }}
